<template>
  <div>
      <MenuList :item="list" v-for="(list,idx) in menuList" :key="idx"></MenuList>
  </div>
</template>
<script>
import MenuList from "../components/MenuList.vue"
export default {
  components:{
    MenuList
  },
  data(){
    return{
      menuList:[{
        label:"24小時標籤",
        children:[
          {
            label:"電玩遊戲",
            children:[
              {
                label:"switch"
              },
              {
                label:"ps4"
              }
            ]
          },
          {
            label:"積木桌遊",
            children:[
              {
                label:"撲克牌",
              },
              {
                label:"德國HABA桌遊"
              }
            ]
          }
        ]
      },
      {
        label:"8小時標籤",
        children:[
          {
            label:"遊戲",
            children:[
              {
                label:"switch2"
              },
              {
                label:"ps42"
              }
            ]
          }
        ]
      }]
    }
  }
}
</script>
<style scoped>

</style>